### ISSUE TITLE
enumerate_param() method parsing fault

### ISSUE THREAD

**Issue by ynalcakan** [czpython/python-amazon-mws#40]
Hello, 

I trying to add product with submit_feed method to US ( amazon.com ) site with 
marketplaceid = ATVPDKIKX0DER but when I call the method enumerate_param()  

enumerate_param returns  this : 
{'MarketplaceIdList.Id.3': 'V', 'MarketplaceIdList.Id.9': 'X', 'MarketplaceIdList.Id.12': 'E', 'MarketplaceIdList.Id.11': 'D', 'MarketplaceIdList.Id.7': 'I', 'MarketplaceIdList.Id.6': 'K', 'MarketplaceIdList.Id.2': 'T', 'MarketplaceIdList.Id.10': '0', 'MarketplaceIdList.Id.4': 'P', 'MarketplaceIdList.Id.5': 'D', 'MarketplaceIdList.Id.13': 'R', 'MarketplaceIdList.Id.8': 'K', 'MarketplaceIdList.Id.1': 'A'}

my code is:
```python
marketplaceid = 'ATVPDKIKX0DER'
feed_type = '_POST_PRODUCT_DATA_'
insert_response = self.client.submit_feed(feed_type=feed_type, feed=feed, marketplaceids=marketplaceid) 
```
this could be my mistake but I couldn't find a solution.

Thanks.

**Comment by bloodywing** [comment]
marketplaceid = 'ATVPDKIKX0DER'
    feed_type = '_POST_PRODUCT_DATA_'
    insert_response = self.client.submit_feed(feed_type=feed_type, feed=feed, marketplaceids=[marketplaceid]) 

Try it like this. See here why it has to be a list http://docs.developer.amazonservices.com/en_US/feeds/Feeds_SubmitFeed.html

**Comment by ynalcakan** [comment]
@bloodywing Thanks, it's my mistake.
