### ISSUE TITLE
remove_empty() is not compatible with Python 3.x 

### ISSUE THREAD

**Issue by madhan-vine** [czpython/python-amazon-mws#49]
`def`remove_empty(d):

```
"""
    Helper function that removes all keys from a dictionary (d),
    that have an empty value.
"""
for key in d.keys():
    if not d[key]:
        del d[key]
return d
```

This utility method is not compatible with Python 3.x. I tested it with sample dict in Python console using Python 2.7.1 and Python 3.5.1. 

Python 3.5.1 throws error:

`
for key in _dict.keys():
     if not _dict[key]:
            del _dict[key]
`

**Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: dictionary changed size during iteration**

My suggestion is instead of **d.keys()**, can use **list(d)** to avoid runtime error and also compatible to Pythonic versions.

[http://stackoverflow.com/questions/11941817/how-to-avoid-runtimeerror-dictionary-changed-size-during-iteration-error](url)

**Comment by GriceTurrble** [comment]
There are some other issues with this project for Py3 inclusion, though it appears that it is no longer maintained.

For this particular function, I am using this as a replacement:

    def remove_empty(d):
        """
        Helper function that returns a copy of a dictionary,
        excluding keys with empty values.
        """
        return {k: v for k, v in d.items() if v}

**Comment by bloodywing** [comment]
The project is still maintained but doesn't has py3 support yet (I don't know why since I changed my fork of it to python 3 too) Also see here: #25
