### ISSUE TITLE
AttributeError: 'module' object has no attribute 'encodebytes'

### ISSUE THREAD

**Issue by prakashkumar163** [czpython/python-amazon-mws#55]
While receiving the mws report data we are getting his error 

 File "/usr/local/lib/python2.7/dist-packages/mws/mws.py", line 344, in get_report
    return self.make_request(data)
  File "/usr/local/lib/python2.7/dist-packages/mws/mws.py", line 213, in make_request
    parsed_response = DataWrapper(data, response.headers)
  File "/usr/local/lib/python2.7/dist-packages/mws/mws.py", line 114, in __init__
    hash_ = calc_md5(self.original)
  File "/usr/local/lib/python2.7/dist-packages/mws/mws.py", line 68, in calc_md5
    **return base64.encodebytes(md.digest()).strip('\n')
AttributeError: 'module' object has no attribute 'encodebytes'**

Please help

**Comment by bloodywing** [comment]
This looks like you are using a python 3 port of the module but your python interpreter is 2.7.
https://github.com/czpython/python-amazon-mws/blob/master/mws/mws.py#L68

**Comment by prakashkumar163** [comment]
Hi 
Yes i am using python 2.7 ,
**Regarding : you are using a python 3 port of the module**
 how to switch to  python 2.7 port from python 3 port

i have just typed **pip install mws**
How can is resolved this issue .

**Comment by bloodywing** [comment]
The repository for your issue is this one https://github.com/jameshiew/mws

You can fix your problem by installing Python 3
or `pip install https://github.com/czpython/python-amazon-mws/archive/master.zip` which would get you the one from this repository here.

**Comment by prakashkumar163** [comment]
Hi Thanks for your prompt response.
i can't switch to python 3, now and i future  also i have to use python2.7 only due to some framework restriction .

Is the library not  logger work for python 2.7, if yes please tell me any alternative 
Is there is a way to run the same in python 2.7

**Comment by bloodywing** [comment]
I wrote you how to use the python 2.7 version, that is the one where you opened this issue. When you run `pip install mws` you'll install a python3 fork of this (https://github.com/jameshiew/mws). An alternative would be boto which has a mws module too: https://github.com/boto/boto and is actively developed.

I might get back into development of this library here too. But I don't have access to an MWS account at the moment.

**Comment by prakashkumar163** [comment]
should i use **pip install python-amazon-mws**  for python 2.7

**Comment by bloodywing** [comment]
No. Use: `pip install https://github.com/czpython/python-amazon-mws/archive/master.zip` the one on pypi is from 2014.

**Comment by prakashkumar163** [comment]
Thanks
